# Generated by Django 5.2.6 on 2025-11-21 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_colegiatura', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('dni', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_rol', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.doctordetalle')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.horario')),
            ],
        ),
        migrations.AddField(
            model_name='doctordetalle',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.entidad'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('clasificacion', models.CharField(choices=[('EMERGENCIA', 'Emergencia'), ('ADULTO_MAYOR', 'Adulto Mayor'), ('REGULAR', 'Regular')], default='REGULAR', max_length=20)),
                ('prioridad', models.PositiveSmallIntegerField(default=3)),
                ('estado', models.CharField(choices=[('EN_ESPERA', 'En espera'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada'), ('NO_SHOW', 'No asistió')], default='EN_ESPERA', max_length=20)),
                ('tipo_cita', models.CharField(choices=[('VIRTUAL', 'Virtual'), ('PRESENCIAL', 'Presencial')], default='PRESENCIAL', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('doctor_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='database.doctorhorario')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_doctor', to='database.entidad')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_paciente', to='database.entidad')),
            ],
            options={
                'ordering': ['prioridad', 'doctor_horario__horario__fecha', 'doctor_horario__horario__hora_inicio', 'fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='doctordetalle',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.especialidad'),
        ),
        migrations.CreateModel(
            name='RolEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.entidad')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.rol')),
            ],
        ),
        migrations.CreateModel(
            name='WaitlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('clasificacion', models.CharField(choices=[('EMERGENCIA', 'Emergencia'), ('ADULTO_MAYOR', 'Adulto Mayor'), ('REGULAR', 'Regular')], default='REGULAR', max_length=20)),
                ('tipo_cita', models.CharField(choices=[('VIRTUAL', 'Virtual'), ('PRESENCIAL', 'Presencial')], default='PRESENCIAL', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('notificado', 'Notificado'), ('aceptado', 'Aceptado'), ('expirado', 'Expirado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('ttl_respuesta_min', models.PositiveIntegerField(default=15)),
                ('doctor_horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_items', to='database.doctorhorario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_items', to='database.entidad')),
            ],
            options={
                'ordering': ['fecha_solicitud'],
            },
        ),
        migrations.AddConstraint(
            model_name='doctorhorario',
            constraint=models.UniqueConstraint(fields=('doctor', 'horario'), name='uq_doctor_horario'),
        ),
        migrations.AlterUniqueTogether(
            name='waitlistitem',
            unique_together={('paciente', 'doctor_horario')},
        ),
    ]
