# Generated by Django 5.2.6 on 2025-11-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='tipo_cita',
            field=models.CharField(choices=[('VIRTUAL', 'Virtual'), ('PRESENCIAL', 'Presencial')], default='PRESENCIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='waitlistitem',
            name='tipo_cita',
            field=models.CharField(choices=[('VIRTUAL', 'Virtual'), ('PRESENCIAL', 'Presencial')], default='PRESENCIAL', max_length=20),
        ),
    ]
