# Generated by Django 5.2.6 on 2025-10-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='tipo',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='presencial', max_length=20, null=True),
        ),
    ]
