# Generated by Django 5.2.6 on 2025-10-22 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_cita_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='doctor_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='database.doctorhorario'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pendiente', 'confirmada'])), fields=('doctor_horario',), name='uq_cita_slot_activo_por_doctor_horario'),
        ),
    ]
