# Generated by Django 5.2.6 on 2025-10-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_cita_doctor_horario_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='doctorhorario',
            constraint=models.UniqueConstraint(fields=('doctor', 'horario'), name='uq_doctor_horario_exact'),
        ),
    ]
