# Generated by Django 5.2.6 on 2025-11-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_historiaclinica_episodioclinico_notaevolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetalle',
            name='cupos_diarios',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctordetalle',
            name='cupos_semanales',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='capacidad_por_hora',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
