# Generated by Django 5.2.6 on 2025-11-27 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_doctordetalle_cupos_diarios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(help_text='Número de teléfono destino', max_length=20)),
                ('tipo', models.CharField(choices=[('recordatorio', 'Recordatorio'), ('instrucciones', 'Instrucciones'), ('llamado', 'Llamado a ingreso')], default='recordatorio', max_length=20)),
                ('mensaje', models.TextField(help_text='Contenido del SMS')),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('entregado', 'Entregado'), ('fallido', 'Fallido'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('sid', models.CharField(blank=True, help_text='SID de Twilio para tracking', max_length=100, null=True)),
                ('intento', models.PositiveSmallIntegerField(default=1, help_text='Número de intento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('respuesta_twilio', models.TextField(blank=True, help_text='Respuesta JSON de Twilio', null=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='database.cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notificaciones', to='database.entidad')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
