# Generated by Django 5.2.6 on 2025-10-25 05:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_doctorhorario_uq_doctor_horario_exact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_llegada', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('en_espera', 'En espera'), ('atendiendo', 'Atendiendo'), ('atendido', 'Atendido'), ('no_show', 'No show')], default='en_espera', max_length=20)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='database.cita')),
            ],
            options={
                'indexes': [models.Index(fields=['hora_llegada'], name='database_ch_hora_ll_3c89f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='WaitlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('notificado', 'Notificado'), ('aceptado', 'Aceptado'), ('expirado', 'Expirado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('ttl_respuesta_min', models.PositiveIntegerField(default=15)),
                ('doctor_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_items', to='database.doctorhorario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_items', to='database.entidad')),
            ],
            options={
                'indexes': [models.Index(fields=['doctor_horario', 'fecha_solicitud'], name='database_wa_doctor__77efa8_idx')],
                'unique_together': {('paciente', 'doctor_horario')},
            },
        ),
    ]
