# Generated by Django 5.2.6 on 2025-10-25 08:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_tipocita_cita_tipo_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_llegada', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('en_espera', 'En espera'), ('atendiendo', 'Atendiendo'), ('atendido', 'Atendido'), ('no_show', 'No show')], default='en_espera', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WaitlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('notificado', 'Notificado'), ('aceptado', 'Aceptado'), ('expirado', 'Expirado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('ttl_respuesta_min', models.PositiveIntegerField(default=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='cita',
            name='tipo_cita',
        ),
        migrations.AlterField(
            model_name='cita',
            name='doctor_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='database.doctorhorario'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='presencial', max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='doctorhorario',
            constraint=models.UniqueConstraint(fields=('doctor', 'horario'), name='uq_doctor_horario_exact'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='database.cita'),
        ),
        migrations.AddField(
            model_name='waitlistitem',
            name='doctor_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_items', to='database.doctorhorario'),
        ),
        migrations.AddField(
            model_name='waitlistitem',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_items', to='database.entidad'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['hora_llegada'], name='database_ch_hora_ll_3c89f2_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlistitem',
            index=models.Index(fields=['doctor_horario', 'fecha_solicitud'], name='database_wa_doctor__77efa8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='waitlistitem',
            unique_together={('paciente', 'doctor_horario')},
        ),
    ]
