# Generated by Django 5.2.6 on 2025-11-29 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_smsnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_consent', models.BooleanField(default=False)),
                ('sms_language', models.CharField(choices=[('es', 'Español'), ('qu', 'Quechua')], default='es', max_length=5)),
                ('consent_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notif_pref', to='database.entidad')),
            ],
        ),
    ]
