# Generated by Django 5.2.6 on 2025-10-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_checkin_waitlistitem_remove_cita_tipo_cita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='codigo_rol',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
