# Generated by Django 5.2.6 on 2025-11-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_rol_codigo_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='ehr_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
