# Generated by Django 5.2.6 on 2025-12-06 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='requiere_derivacion',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('valido', models.BooleanField(default=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones', to='database.especialidad')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones', to='database.entidad')),
            ],
        ),
    ]
