# Generated by Django 5.2.6 on 2025-12-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_especialidad_requiere_derivacion_derivacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='recordatorio_2h_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cita',
            name='recordatorio_48h_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('EN_ESPERA', 'En espera'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada'), ('NO_SHOW', 'No asistió'), ('confirmada', 'Confirmada')], default='EN_ESPERA', max_length=20),
        ),
        migrations.AlterField(
            model_name='smsnotification',
            name='tipo',
            field=models.CharField(choices=[('recordatorio', 'Recordatorio'), ('instrucciones', 'Instrucciones'), ('llamado', 'Llamado a ingreso'), ('encuesta', 'Encuesta')], default='recordatorio', max_length=20),
        ),
    ]
