# Generated by Django 5.2.6 on 2025-12-10 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_cita_recordatorio_2h_enviado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(default='REPROGRAMACIÓN', max_length=50)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('valor_anterior', models.JSONField(blank=True, null=True)),
                ('valor_nuevo', models.JSONField(blank=True, null=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='database.cita')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.entidad')),
            ],
            options={
                'ordering': ['-fecha_evento'],
            },
        ),
    ]
